/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import entity.ChuyenManHinhController;
import entity.danhmuc;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Mark
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        ChuyenManHinhController cmh = new ChuyenManHinhController(jPanelview);
        List<danhmuc> lstdanhmuc = new ArrayList<>(); 
        lstdanhmuc.add(new danhmuc("trangchu",jpntrangchu,jlbtrangchu));
        cmh.setView(jpntrangchu,jlbtrangchu);
        lstdanhmuc.add(new danhmuc("quanlikhosach",jpnkhosach,jlbkhosach));
        lstdanhmuc.add(new danhmuc("quanlimuonsach",jpnmuonsach,jlbmuonsach));
        lstdanhmuc.add(new danhmuc("quanlinhanvien",jpnnhanvien,jlbnhanvien));
        lstdanhmuc.add(new danhmuc("quanlinguoimuon",jpnnguoimuon,jlbnguoimuon));
        cmh.setEvent(lstdanhmuc);
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpn1 = new javax.swing.JPanel();
        jpnmuonsach = new javax.swing.JPanel();
        jlbmuonsach = new javax.swing.JLabel();
        jpntrangchu = new javax.swing.JPanel();
        jlbtrangchu = new javax.swing.JLabel();
        jpnkhosach = new javax.swing.JPanel();
        jlbkhosach = new javax.swing.JLabel();
        jpnnhanvien = new javax.swing.JPanel();
        jlbnhanvien = new javax.swing.JLabel();
        jpnnguoimuon = new javax.swing.JPanel();
        jlbnguoimuon = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanelview = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpn1.setBackground(new java.awt.Color(0, 153, 153));
        jpn1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbmuonsach.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbmuonsach.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbmuonsach.setText("Quản Lí Mượn Sách");

        javax.swing.GroupLayout jpnmuonsachLayout = new javax.swing.GroupLayout(jpnmuonsach);
        jpnmuonsach.setLayout(jpnmuonsachLayout);
        jpnmuonsachLayout.setHorizontalGroup(
            jpnmuonsachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbmuonsach, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        jpnmuonsachLayout.setVerticalGroup(
            jpnmuonsachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbmuonsach, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jpn1.add(jpnmuonsach, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 170, 50));

        jlbtrangchu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbtrangchu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbtrangchu.setText("Trang Chủ");

        javax.swing.GroupLayout jpntrangchuLayout = new javax.swing.GroupLayout(jpntrangchu);
        jpntrangchu.setLayout(jpntrangchuLayout);
        jpntrangchuLayout.setHorizontalGroup(
            jpntrangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpntrangchuLayout.createSequentialGroup()
                .addComponent(jlbtrangchu, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpntrangchuLayout.setVerticalGroup(
            jpntrangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbtrangchu, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jpn1.add(jpntrangchu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 170, 50));

        jlbkhosach.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbkhosach.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbkhosach.setText("Quản Lí Kho Sách");

        javax.swing.GroupLayout jpnkhosachLayout = new javax.swing.GroupLayout(jpnkhosach);
        jpnkhosach.setLayout(jpnkhosachLayout);
        jpnkhosachLayout.setHorizontalGroup(
            jpnkhosachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbkhosach, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        jpnkhosachLayout.setVerticalGroup(
            jpnkhosachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbkhosach, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jpn1.add(jpnkhosach, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 170, 50));

        jlbnhanvien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbnhanvien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbnhanvien.setText("Quản Lí Nhân Viên");
        jlbnhanvien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jpnnhanvienLayout = new javax.swing.GroupLayout(jpnnhanvien);
        jpnnhanvien.setLayout(jpnnhanvienLayout);
        jpnnhanvienLayout.setHorizontalGroup(
            jpnnhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnnhanvienLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlbnhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpnnhanvienLayout.setVerticalGroup(
            jpnnhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnnhanvienLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlbnhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpn1.add(jpnnhanvien, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 170, 50));

        jlbnguoimuon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbnguoimuon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbnguoimuon.setText("Quản Lí Người Mượn");
        jlbnguoimuon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jpnnguoimuonLayout = new javax.swing.GroupLayout(jpnnguoimuon);
        jpnnguoimuon.setLayout(jpnnguoimuonLayout);
        jpnnguoimuonLayout.setHorizontalGroup(
            jpnnguoimuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnnguoimuonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlbnguoimuon, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpnnguoimuonLayout.setVerticalGroup(
            jpnnguoimuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnnguoimuonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlbnguoimuon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpn1.add(jpnnguoimuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 170, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Đăng Xuất");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpn1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 170, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Quản Lí Thư Viện");
        jpn1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 160, -1));

        getContentPane().add(jpn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 210, 640));

        jPanelview.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelviewLayout = new javax.swing.GroupLayout(jPanelview);
        jPanelview.setLayout(jPanelviewLayout);
        jPanelviewLayout.setHorizontalGroup(
            jPanelviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        jPanelviewLayout.setVerticalGroup(
            jPanelviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelview, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 830, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelview;
    private javax.swing.JLabel jlbkhosach;
    private javax.swing.JLabel jlbmuonsach;
    private javax.swing.JLabel jlbnguoimuon;
    private javax.swing.JLabel jlbnhanvien;
    private javax.swing.JLabel jlbtrangchu;
    private javax.swing.JPanel jpn1;
    private javax.swing.JPanel jpnkhosach;
    private javax.swing.JPanel jpnmuonsach;
    private javax.swing.JPanel jpnnguoimuon;
    private javax.swing.JPanel jpnnhanvien;
    private javax.swing.JPanel jpntrangchu;
    // End of variables declaration//GEN-END:variables
}
