/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import entity.ChuyenManHinhController;
import entity.danhmuc;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Mark
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        ChuyenManHinhController cmh = new ChuyenManHinhController(jPanelview);
        List<danhmuc> lstdanhmuc = new ArrayList<>(); 
        lstdanhmuc.add(new danhmuc("trangchu",jpntrangchu,jlbtrangchu));
        cmh.setView(jpntrangchu,jlbtrangchu);
//        lstdanhmuc.add(new danhmuc("quanlikhosach",jpnkhosach,jlbkhosach));
        lstdanhmuc.add(new danhmuc("quanlimuonsach",jpnmuonsach,jlbmuonsach));
        lstdanhmuc.add(new danhmuc("thongke",jpthongke,jlbthongke));
        lstdanhmuc.add(new danhmuc("quanlinguoimuon",jpnnguoimuon,jlbnguoimuon));
        lstdanhmuc.add(new danhmuc("quanlinhnvien",jpnhanvien,jlbnhanvien));
        lstdanhmuc.add(new danhmuc("quanlitaikhoan",jptaikhoan,jlbtaikhoan));
        cmh.setEvent(lstdanhmuc);
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpn1 = new javax.swing.JPanel();
        jpnmuonsach = new javax.swing.JPanel();
        jlbmuonsach = new javax.swing.JLabel();
        jpntrangchu = new javax.swing.JPanel();
        jlbtrangchu = new javax.swing.JLabel();
        jpthongke = new javax.swing.JPanel();
        jlbthongke = new javax.swing.JLabel();
        jpnnguoimuon = new javax.swing.JPanel();
        jlbnguoimuon = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jpnhanvien = new javax.swing.JPanel();
        jlbnhanvien = new javax.swing.JLabel();
        jptaikhoan = new javax.swing.JPanel();
        jlbtaikhoan = new javax.swing.JLabel();
        jPanelview = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpn1.setBackground(new java.awt.Color(0, 153, 153));
        jpn1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbmuonsach.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbmuonsach.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbmuonsach.setText("Quản Lí Mượn Sách");

        javax.swing.GroupLayout jpnmuonsachLayout = new javax.swing.GroupLayout(jpnmuonsach);
        jpnmuonsach.setLayout(jpnmuonsachLayout);
        jpnmuonsachLayout.setHorizontalGroup(
            jpnmuonsachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnmuonsachLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlbmuonsach, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpnmuonsachLayout.setVerticalGroup(
            jpnmuonsachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnmuonsachLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlbmuonsach, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpn1.add(jpnmuonsach, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 170, 60));

        jlbtrangchu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbtrangchu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbtrangchu.setText("Trang Chủ");

        javax.swing.GroupLayout jpntrangchuLayout = new javax.swing.GroupLayout(jpntrangchu);
        jpntrangchu.setLayout(jpntrangchuLayout);
        jpntrangchuLayout.setHorizontalGroup(
            jpntrangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpntrangchuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlbtrangchu, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpntrangchuLayout.setVerticalGroup(
            jpntrangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpntrangchuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlbtrangchu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpn1.add(jpntrangchu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 170, 60));

        jlbthongke.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbthongke.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbthongke.setText("Thống Kê");
        jlbthongke.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jpthongkeLayout = new javax.swing.GroupLayout(jpthongke);
        jpthongke.setLayout(jpthongkeLayout);
        jpthongkeLayout.setHorizontalGroup(
            jpthongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpthongkeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlbthongke, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpthongkeLayout.setVerticalGroup(
            jpthongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpthongkeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlbthongke, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpn1.add(jpthongke, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 170, 60));

        jlbnguoimuon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbnguoimuon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbnguoimuon.setText("Quản Lí Người Mượn");
        jlbnguoimuon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jpnnguoimuonLayout = new javax.swing.GroupLayout(jpnnguoimuon);
        jpnnguoimuon.setLayout(jpnnguoimuonLayout);
        jpnnguoimuonLayout.setHorizontalGroup(
            jpnnguoimuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnnguoimuonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlbnguoimuon, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpnnguoimuonLayout.setVerticalGroup(
            jpnnguoimuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnnguoimuonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlbnguoimuon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpn1.add(jpnnguoimuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 170, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Đăng Xuất");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpn1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 170, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Quản Lí Thư Viện");
        jpn1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 160, -1));

        jlbnhanvien.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jlbnhanvien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbnhanvien.setText("Quản Lí Nhân Viên");

        javax.swing.GroupLayout jpnhanvienLayout = new javax.swing.GroupLayout(jpnhanvien);
        jpnhanvien.setLayout(jpnhanvienLayout);
        jpnhanvienLayout.setHorizontalGroup(
            jpnhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnhanvienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbnhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnhanvienLayout.setVerticalGroup(
            jpnhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnhanvienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbnhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpn1.add(jpnhanvien, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 160, 50));

        jlbtaikhoan.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jlbtaikhoan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbtaikhoan.setText("Quản Lí Tài Khoản");

        javax.swing.GroupLayout jptaikhoanLayout = new javax.swing.GroupLayout(jptaikhoan);
        jptaikhoan.setLayout(jptaikhoanLayout);
        jptaikhoanLayout.setHorizontalGroup(
            jptaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbtaikhoan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        jptaikhoanLayout.setVerticalGroup(
            jptaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbtaikhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jpn1.add(jptaikhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 160, 40));

        getContentPane().add(jpn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 590));

        jPanelview.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelviewLayout = new javax.swing.GroupLayout(jPanelview);
        jPanelview.setLayout(jPanelviewLayout);
        jPanelviewLayout.setHorizontalGroup(
            jPanelviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        jPanelviewLayout.setVerticalGroup(
            jPanelviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelview, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 1010, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
      int choice = JOptionPane.showConfirmDialog(
        this,
        "Bạn có chắc chắn muốn đăng xuất?",
        "Xác nhận đăng xuất",
        JOptionPane.YES_NO_OPTION
    );
    
    if (choice == JOptionPane.YES_OPTION) {
        // Create new choose_signin instance
        choose_signin cs = new choose_signin();
        
        // Hide/dispose the current Menu window 
        this.dispose();
        
        // Show the choose_signin window
        cs.setVisible(true);
    }
        
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelview;
    private javax.swing.JLabel jlbmuonsach;
    private javax.swing.JLabel jlbnguoimuon;
    private javax.swing.JLabel jlbnhanvien;
    private javax.swing.JLabel jlbtaikhoan;
    private javax.swing.JLabel jlbthongke;
    private javax.swing.JLabel jlbtrangchu;
    private javax.swing.JPanel jpn1;
    private javax.swing.JPanel jpnhanvien;
    private javax.swing.JPanel jpnmuonsach;
    private javax.swing.JPanel jpnnguoimuon;
    private javax.swing.JPanel jpntrangchu;
    private javax.swing.JPanel jptaikhoan;
    private javax.swing.JPanel jpthongke;
    // End of variables declaration//GEN-END:variables
}
