/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import DAO.NguoiMuonDAO;
import DAO.SachDAO;
import entity.NguoiMuon;
import entity.Sach;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Mark
 */
public class QuanLINguoiMuon extends javax.swing.JPanel {

    /**
     * Creates new form QuanLINguoiMuon
     */
    public QuanLINguoiMuon() {
        initComponents();
        getall();
    }
    public void getall() {
        NguoiMuonDAO dao = new NguoiMuonDAO();
        List<NguoiMuon> NguoiMuonList = dao.getAll(); // Lấy danh sách sách từ cơ sở dữ liệu
        DefaultTableModel model = new DefaultTableModel();
        
        // Thêm cột vào model
        model.addColumn("Tên Người Mượn");
        model.addColumn("Quê Quán");
        model.addColumn("Số Điện Thoại");
        model.addColumn("Gmail");
        
        model.addColumn("id");
// Thêm cột Giá nếu có

        // Thêm dữ liệu vào model
        for (NguoiMuon n : NguoiMuonList) {
            model.addRow(new Object[]{
                 
                n.getTenNguoiMuon(),           // ID của sách
                n.getQueQuan(),
                n.getSdt(),
                n.getGmail(),
               
                n.getIdNguoiMuon()

               
                          // Giá
            });
        }

        jTable1.setModel(model); // Gán model vào jTable1 để hiển thị dữ liệu
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản Lí Người Mượn");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Tên người mượn", "Quê quán ", "Số điện thoại", "Gmail", "Trạng thái", "id"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 136, 77), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(255, 0, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Sửa ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 100, 50));

        jButton3.setBackground(new java.awt.Color(255, 0, 51));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("Xoá");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 100, 60));

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Thêm ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 90, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 136, 77), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Tên người mượn");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Quê quán");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Số điện thoại");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Gmail");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 150, -1));
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 170, -1));
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 150, -1));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 170, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Ngày mượn");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Ngày trả");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));
        jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 150, -1));
        jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 150, -1));
        jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 170, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Số lượng mượn");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, -1));
        jPanel2.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 150, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("ID sách");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 59, -1));
        jPanel2.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 160, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("ID");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 88, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(188, 188, 188))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(39, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    try {
    // Lấy giá trị từ các trường JTextField và loại bỏ khoảng trắng đầu/cuối
    int id = Integer.parseInt(jTextField7.getText().trim());
    String ten = jTextField1.getText().trim();
    String quequan = jTextField2.getText().trim();
    String sdt = jTextField3.getText().trim();
    String gmail = jTextField4.getText().trim();
    int idsach = Integer.parseInt(jTextField9.getText().trim());
    
    // Chuyển đổi từ String sang LocalDate
    String ngaymuonStr = jTextField5.getText().trim();
    String ngaytraStr = jTextField6.getText().trim();
    int soluongmuon = Integer.parseInt(jTextField8.getText().trim()); // Chuyển đổi số lượng mượn từ JTextField

    // Khởi tạo LocalDate từ chuỗi nhập vào
    LocalDate ngaymuon = null;
    LocalDate ngaytra = null;

    // Kiểm tra và chuyển đổi ngày mượn
    if (!ngaymuonStr.isEmpty()) {
        ngaymuon = LocalDate.parse(ngaymuonStr); // Chuyển đổi từ String thành LocalDate
    }

    // Kiểm tra và chuyển đổi ngày trả (nếu có)
    if (!ngaytraStr.isEmpty()) {
        ngaytra = LocalDate.parse(ngaytraStr); // Chuyển đổi từ String thành LocalDate
    }

    // Tạo đối tượng DAO
    NguoiMuonDAO dao = new NguoiMuonDAO();
    SachDAO sachdao = new SachDAO();
    
    // Tìm quyển sách theo ID
    Sach sach = sachdao.findById(idsach);
    
    // Kiểm tra xem sách có đủ số lượng hay không
    if (sach != null && sach.getSoluong() >= soluongmuon) {
        // Tìm người mượn theo ID
        NguoiMuon nguoi = dao.findById(id);

        if (nguoi == null) {
            // Nếu người mượn không tồn tại, tạo đối tượng mới
            nguoi = new NguoiMuon(ten, ngaymuon, ngaytra, quequan, sdt, gmail, soluongmuon);

            // Lưu người mượn mới vào cơ sở dữ liệu
            boolean saved = dao.save(nguoi);
            
            if (saved) {
                // Sau khi lưu người mượn, giảm số lượng sách
                sach.setSoluong(sach.getSoluong() - soluongmuon);
                
                // Cập nhật số lượng sách vào cơ sở dữ liệu
                sachdao.updateBook(sach);
                
                JOptionPane.showMessageDialog(null, "Thêm người mượn thành công!");
                getall(); // Cập nhật giao diện với thông tin mới
            } else {
                JOptionPane.showMessageDialog(null, "Thêm người mượn thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "ID người mượn đã tồn tại", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        // Nếu sách không đủ số lượng
        JOptionPane.showMessageDialog(null, "Sách không đủ số lượng để mượn!", "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(null, "Vui lòng nhập số hợp lệ cho ID và số lượng mượn!", "Lỗi", JOptionPane.ERROR_MESSAGE);
} catch (DateTimeParseException e) {
    JOptionPane.showMessageDialog(null, "Vui lòng nhập ngày hợp lệ cho ngày mượn và ngày trả!", "Lỗi", JOptionPane.ERROR_MESSAGE);
} catch (Exception e) {
    e.printStackTrace(); // In ra lỗi cho quá trình gỡ lỗi
    JOptionPane.showMessageDialog(null, "Đã có lỗi xảy ra, vui lòng thử lại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
}

 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
        // Lấy giá trị từ các trường JTextField và loại bỏ khoảng trắng đầu/cuối
        int id = Integer.parseInt(jTextField7.getText().trim());
        String ten = jTextField1.getText().trim();
        String quequan = jTextField2.getText().trim();
        String sdt = jTextField3.getText().trim();
        String gmail = jTextField4.getText().trim();
        
        // Chuyển đổi từ String sang LocalDate
        String ngaymuonStr = jTextField5.getText().trim();
        String ngaytraStr = jTextField6.getText().trim();
        int soluongmuon = Integer.parseInt(jTextField8.getText().trim()); 
        // Khởi tạo LocalDate từ chuỗi nhập vào
        LocalDate ngaymuon = null;
        LocalDate ngaytra = null;

        // Kiểm tra và chuyển đổi ngày mượn
        if (!ngaymuonStr.isEmpty()) {
            ngaymuon = LocalDate.parse(ngaymuonStr); // Chuyển đổi từ String thành LocalDate
        }

        // Kiểm tra và chuyển đổi ngày trả (nếu có)
        if (!ngaytraStr.isEmpty()) {
            ngaytra = LocalDate.parse(ngaytraStr); // Chuyển đổi từ String thành LocalDate
        }

        // Tạo đối tượng DAO
        NguoiMuonDAO dao = new NguoiMuonDAO();

        // Tìm người mượn theo ID
        NguoiMuon nguoi = dao.findById(id);

        if (nguoi != null) {
            // Nếu người mượn đã tồn tại, cập nhật thông tin người mượn
            nguoi.setTenNguoiMuon(ten);
            nguoi.setNgayMuon(ngaymuon);
            nguoi.setNgayTra(ngaytra);
            nguoi.setQueQuan(quequan);
            nguoi.setSdt(sdt);
            nguoi.setGmail(gmail);
            nguoi.setSoLuongMuon(soluongmuon);

            boolean updated = dao.updateNguoiMuon(nguoi); // Cập nhật người mượn vào cơ sở dữ liệu
            if (updated) {
                JOptionPane.showMessageDialog(null, "Cập nhật người mượn thành công!");
                getall(); // Cập nhật lại danh sách
            } else {
                JOptionPane.showMessageDialog(null, "Cập nhật người mượn thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "ID không tồn tại", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Vui lòng nhập số hợp lệ cho ID!", "Lỗi", JOptionPane.ERROR_MESSAGE);
    } catch (DateTimeParseException e) {
        JOptionPane.showMessageDialog(null, "Vui lòng nhập ngày hợp lệ cho ngày mượn và ngày trả!", "Lỗi", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        e.printStackTrace(); // In ra lỗi cho quá trình gỡ lỗi
        JOptionPane.showMessageDialog(null, "Đã có lỗi xảy ra, vui lòng thử lại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
        // Lấy chỉ số của hàng được chọn trong JTable
        int selectedRow = jTable1.getSelectedRow();

        // Kiểm tra nếu không có dòng nào được chọn
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn người mượn từ bảng!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Lấy ID từ cột đầu tiên của hàng đã chọn
        int id = (int) jTable1.getValueAt(selectedRow, 5);

        // Tạo đối tượng DAO
        NguoiMuonDAO dao = new NguoiMuonDAO();

        // Gọi hàm xóa
        boolean deleted = dao.deleteNguoiMuon(id);

        if (deleted) {
            JOptionPane.showMessageDialog(null, "Xóa người mượn thành công!");
            getall(); // Cập nhật lại danh sách sau khi xóa
        } else {
            JOptionPane.showMessageDialog(null, "Xóa người mượn thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception e) {
        e.printStackTrace(); // In ra lỗi cho quá trình gỡ lỗi
        JOptionPane.showMessageDialog(null, "Đã có lỗi xảy ra, vui lòng thử lại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
