/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import DAO.nguoidungDAO;
import entity.nguoidung;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mark
 */
public class QuanLiTaiKhoan extends javax.swing.JPanel {

    /**
     * Creates new form QuanLiTaiKhoan
     */
    public QuanLiTaiKhoan() {
        initComponents();
        getall();
    }

    public void getall() {
        nguoidungDAO dao = new nguoidungDAO();
        List<nguoidung> List = dao.getAll(); // Lấy danh sách sách từ cơ sở dữ liệu
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("id");
        // Thêm cột vào model
        model.addColumn("Tên Tài Khoản");
        model.addColumn("Mật Khẩu");
        model.addColumn("Gmail");
        model.addColumn("Sdt");

        // Thêm dữ liệu vào model
        for (nguoidung nguoi : List) {
            model.addRow(new Object[]{
                nguoi.getManguoidung(),
                nguoi.getTentk(), // ID của sách
                nguoi.getMatkhau(), // Tên sách

                nguoi.getEmail(), // Năm xuất bản
                nguoi.getSodienthoai()

            });
        }

        jTable1.setModel(model); // Gán model vào jTable1 để hiển thị dữ liệu
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 204));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản Lí Tai Khoản");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên tài khoản", "Mật khẩu", "Gmail", "Số điện thoại"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Sửa ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 44, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Xoá");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 44, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Thêm ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 44, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Mật khẩu");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel3.setText("Gmail");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel4.setText("Số điện thoại");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 280, -1));
        jPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 280, -1));
        jPanel3.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 270, -1));

        jLabel5.setText("Tài khoản");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 70, -1));
        jPanel3.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 280, -1));
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         int row = jTable1.getSelectedRow(); // Lấy chỉ số dòng được chọn
    if (row == -1) {
        JOptionPane.showMessageDialog(null, "Vui lòng chọn một tài khoản để sửa.");
        return;
    }

    
    // Bước 3: Điền thông tin vào các JTextField để người dùng có thể sửa
    

    // Bước 4: Khi nhấn nút "Sửa" (button2), thực hiện cập nhật vào CSDL
    // Lấy các giá trị mới từ JTextField
    String newTentk = jTextField4.getText();
    String newMatkhau = jTextField1.getText();
    String newEmail = jTextField2.getText();
    String newSodienthoai = jTextField3.getText();

    // Bước 5: Kiểm tra các trường không rỗng
    if (newTentk.isEmpty() || newMatkhau.isEmpty() || newEmail.isEmpty() || newSodienthoai.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin.");
        return;
    }

    // Bước 6: Tạo đối tượng nguoidung mới và cập nhật các trường
    nguoidung nguoiDung = new nguoidung();
    nguoiDung.setManguoidung(Integer.parseInt(jTable1.getValueAt(row, 0).toString())); // Lấy ID từ bảng
    nguoiDung.setTentk(newTentk);
    nguoiDung.setMatkhau(newMatkhau);
    nguoiDung.setEmail(newEmail);
    nguoiDung.setSodienthoai(newSodienthoai);

    // Bước 7: Cập nhật thông tin vào cơ sở dữ liệu
    nguoidungDAO dao = new nguoidungDAO();
    boolean ketQua = dao.update(nguoiDung);

    // Bước 8: Thông báo kết quả
    if (ketQua) {
        JOptionPane.showMessageDialog(null, "Cập nhật thành công.");
        getall(); // Cập nhật lại bảng
    } else {
        JOptionPane.showMessageDialog(null, "Cập nhật thất bại.");
    }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow(); // Lấy chỉ số dòng được chọn
    if (row == -1) {
        JOptionPane.showMessageDialog(null, "Vui lòng chọn một tài khoản để xóa.");
        return;
    }

    // Bước 2: Xác nhận hành động xóa
    int confirm = JOptionPane.showConfirmDialog(null, 
            "Bạn có chắc chắn muốn xóa tài khoản này?", 
            "Xóa tài khoản", 
            JOptionPane.YES_NO_OPTION);
    if (confirm != JOptionPane.YES_OPTION) {
        return; // Nếu người dùng không đồng ý xóa, thì thoát
    }

    // Bước 3: Lấy ID của người dùng từ bảng (từ cột 0)
    int manguoidung = Integer.parseInt(jTable1.getValueAt(row, 0).toString());

    // Bước 4: Xóa dữ liệu khỏi cơ sở dữ liệu
    nguoidungDAO dao = new nguoidungDAO();
    boolean ketQua = dao.delete(manguoidung); // Gọi phương thức xóa trong DAO

    // Bước 5: Thông báo kết quả
    if (ketQua) {
        JOptionPane.showMessageDialog(null, "Xóa thành công.");
        getall(); // Cập nhật lại bảng sau khi xóa
    } else {
        JOptionPane.showMessageDialog(null, "Xóa thất bại.");
    }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
String tenTaiKhoan = jTextField4.getText();  // txtTenTaiKhoan là JTextField cho tên tài khoản
    String matKhau = jTextField1.getText();            // txtMatKhau là JTextField cho mật khẩu
    String email = jTextField2.getText();                // txtEmail là JTextField cho email
    String soDienThoai = jTextField3.getText();    // txtSoDienThoai là JTextField cho số điện thoại

    // Kiểm tra nếu các trường bắt buộc không rỗng
    if (tenTaiKhoan.isEmpty() || matKhau.isEmpty() || email.isEmpty() || soDienThoai.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin.");
        return;
    }

    // Tạo đối tượng nguoidung mới và gán các giá trị
    nguoidung nguoiDungMoi = new nguoidung();
    nguoiDungMoi.setTentk(tenTaiKhoan);
    nguoiDungMoi.setMatkhau(matKhau);
    nguoiDungMoi.setEmail(email);
    nguoiDungMoi.setSodienthoai(soDienThoai);

    // Thêm người dùng vào cơ sở dữ liệu thông qua DAO
    nguoidungDAO dao = new nguoidungDAO();
    boolean isAdded = dao.save(nguoiDungMoi);  // Giả sử bạn có phương thức add trong nguoidungDAO để thêm người dùng mới

    // Thông báo kết quả thêm mới
    if (isAdded) {
        JOptionPane.showMessageDialog(null, "Thêm mới người dùng thành công.");
        getall();  // Cập nhật lại danh sách người dùng sau khi thêm mới
    } else {
        JOptionPane.showMessageDialog(null, "Lỗi khi thêm người dùng.");
    }

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
